### ISSUE TITLE
Clarify usage of `m2t` container object

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#477]
Let's discuss the usage of the `m2` container object. It's history and some of it's purposes are described by @egeerardyn in comment https://github.com/matlab2tikz/matlab2tikz/commit/08dbd7c52197949a1a9abbdc093255e78ba84b89#commitcomment-8832480.

I understand now that it is used to remove the unwanted use of global variables ( :+1: ). Ideally it should at least be documented somewhere what kind of features make use of it and what general purpose it serves. I am unsure whether the code or the wiki here is better suited.

Moving away from this approach is certainly a difficult task and I would not suggest doing it right now. But I propose that we have a look at all the (new) subfunctions and check, if it is needed to pass the `m2t` object (check both for the **parameter** `m2t` and the **returned object** `m2t`).
## Todo list

@egeerardyn: I'm hijacking the first post to add a little TODO list for clarity.
- [x] [Group some m2t fields into an `About` sub-struct](https://github.com/matlab2tikz/matlab2tikz/issues/477#issuecomment-67893096) (this is tackled in a private branch for the updater)
- [ ] [Maybe even remove some of those fields](https://github.com/matlab2tikz/matlab2tikz/issues/477#issuecomment-67897064)
- [ ] [Put `axes`-related fields in `axesContainers{end}`](https://github.com/matlab2tikz/matlab2tikz/issues/477#issuecomment-69473097)
- [ ] Remove `m2t` input/output parameter in some functions where this is not necessary (beware: in some functions `m2t` might be needed in the future. See below for discussion).

**Comment by okomarov** [comment]
I also noted that lots of axis specific stuff is in `m2t` rather than under `m2t.axesContainers{end}`:
```matlab
             axesBoundingBox: [0 0 1 1]
              axesContainers: {[1x1 struct]}
         gcaAssociatedLegend: []
                  unitlength: [1x1 struct]
               xAxisReversed: 0
               yAxisReversed: 0
               zAxisReversed: 0
```

**Comment by okomarov** [comment]
I would also suggest to localize the color definitions with the suggestion in: 
http://tex.stackexchange.com/questions/24434/how-to-specify-a-fill-color-in-rgb-format-in-a-node-in-tikzpicture

In other words, get rid of the global `m2t.extraRgbColorNames`, `m2t.extraRgbColorSpecs` and use the RGB specification directly inside the plot:
    \addplot[fill={rgb:red,4;green,2;yellow,1},...]
