### ISSUE TITLE
Resolve hash mismatches between different platforms and program versions

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#552]
See #485; #542 is related

Let's first collect the tex output from the `converted` folder and then start a systematic approach to eliminate the issues leading to md5 hash mismatches.

- [x] Color definitions are present in R2014b --> we might set the `defaultAxesColorOrder` (`get(0,'defaultAxesColorOrder')`, ref [here](http://de.mathworks.com/help/matlab/creating_plots/defining-the-color-of-lines-for-plotting.html)), fix at #641 
- [x] `width`, `height` and `at` don't match concerning their values, influenced by `ScreenPixelsPerInch`, fix at #641 
- [ ] `xtick` values differ; this is expected since octave here simply behaves differently. Course of action?
- [ ] `xlabel style`. `title style` and `legend style` is set explicitly/differently for R2014b (#542 could resolve this)
- [ ] `xlabel` is parsed differently. One time newlines are printed and once `\\[1ex]` is added

If we want to stick to md5sums for comparison, we have to tackle all of those bullet points. How should we proceed with the differing `xtick` values?

**Comment by okomarov** [comment]
With reference to the mismatching hashes on R2014b - Win7 64b reported in https://github.com/matlab2tikz/matlab2tikz/pull/485#issuecomment-76407920, find attached the zipped converted folder: https://www.dropbox.com/s/6scbblpjiemsv4v/Win7_R2014b_converted.zip?dl=0

**Comment by PeterPablo** [comment]
Did you test with https://github.com/egeerardyn/matlab2tikz/commit/a713c6656537c57427c90da2fdea84f6c6723db2?

**Comment by PeterPablo** [comment]
Alright. Since the updated test environment is now in use, we may begin...
I ran `testGraphical(1)` on ubuntu with both `octave 3.8.2` and `MATLAB R2014b` and diffed the output:
```
--- test1_R2014b.tex	2015-03-03 10:05:04.811623309 +0100
+++ test1_octave.tex	2015-03-03 10:03:11.491625188 +0100
@@ -9,33 +9,31 @@
 \usepackage{amsmath}
 
 \begin{document}
-\definecolor{mycolor1}{rgb}{0.00000,0.44700,0.74100}%
-\definecolor{mycolor2}{rgb}{0.85000,0.32500,0.09800}%
-%
 \begin{tikzpicture}
 
 \begin{axis}[%
-width=4.568421in,
-height=3.463657in,
-at={(0.766316in,0.556866in)},
+width=4.525281in,
+height=3.522212in,
+at={(0.75908in,0.481723in)},
 scale only axis,
 xmin=1,
 xmax=5,
-xtick={1,1.5,2,2.5,3,3.5,4,4.5,5},
+xtick={1,2,3,4,5},
 xticklabels={\empty},
-xlabel style={align=center},
-xlabel={one\\[1ex]two\\[1ex]three},
+xlabel={one
+two
+three},
 ymin=-1.5,
 ymax=1.5,
 ytick={\empty},
 ylabel style={align=center},
 ylabel={one\\[1ex]$^\circ\text{ }\infty$\\[1ex]three},
 axis background/.style={fill=white},
-title style={font=\bfseries,align=center},
+title style={align=center},
 title={multline\\[1ex]title},
-legend style={legend cell align=left,align=left,draw=white!15!black}
+legend style={legend cell align=right,align=right,legend plot pos=left,draw=black}
 ]
-\addplot [color=mycolor1,solid,mark=asterisk,mark options={solid}]
+\addplot [color=blue,solid,mark=asterisk,mark options={solid}]
   table[row sep=crcr]{%
 1	0\\
 2	1\\
@@ -45,7 +43,7 @@
 };
 \addlegendentry{multi-line legends\\$\text{do work 2}^\text{2}\text{=4}$};
 
-\addplot [color=mycolor2,dashed,mark=x,mark options={solid}]
+\addplot [color=blue,dashed,mark=x,mark options={solid}]
   table[row sep=crcr]{%
 1	-1.5\\
 2	0.5\\
```

- [ ] Color definitions are present in R2014b --> we might set the `defaultAxesColorOrder` (`get(0,'defaultAxesColorOrder')`, ref [here](http://de.mathworks.com/help/matlab/creating_plots/defining-the-color-of-lines-for-plotting.html))
- [ ] `width`, `height` and `at` don't match concerning their values
- [ ] `xtick` values differ; this is expected since octave here simply behaves differently. Course of action?
- [ ] `xlabel style`. `title style` and `legend style` is set explicitly/differently for R2014b (#542 could resolve this)
- [ ] `xlabel` is parsed differently. One time newlines are printed and once `\\[1ex]` is added

If we want to stick to md5sums for comparison, we have to tackle all of those bullet points. How should we proceed with the differing `xtick` values?

**Comment by PeterPablo** [comment]
First bullet point can be addressed by
```defaultAxesColorOrder = [0,0,1;0,0.500,0;1,0,0;0,0.750,0.750;0.750,0,0.750;0.750,0.750,0;0.250,0.250,0.250;]; set(0,'defaultAxesColorOrder',defaultAxesColorOrder);```.
This should go in #542.

**Comment by egeerardyn** [comment]
@PeterPablo I think it will be nearly impossible to make sure that every environment returns the same output since these environments are inherently different (either by design or by accident). That is not our responsibility, but an upstream one.

Making sure that every version of MATLAB/Octave produces the same output, takes a lot of work, but adds little: we will still need to test all platforms to make sure that these respond in the same way after each change. So, while it might be interesting to determine where these mismatches come from, I think it is more productive to focus our effort on making sure that every single environment (e.g. MATLAB R2014b) produces the same output regardless of the global state a developer has set. Note that this is not the same as #542 but rather a patch-up for the same underlying issue.

To that end, I would suggest o change the testing code such that:
* global state is saved (e.g. to a MAT file)
* global state is reset to a known condition (e.g. empty or a reasonable value)
* run the tests
* global state is restored afterwards

**Comment by PeterPablo** [comment]
Concerning the second bullet point `width`, `height`, `at`. Running `testHeadless(1)` should remove dimensions, though this is not entirely the case:
```
width=0.995413\figurewidth,
height=\figureheight,
at={(0\figurewidth,0\figureheight)},
```
The factor in `width` differs between Matlab and octave and is a likely cause for unreliable tests (different operating system, different graphic system, ...).
Personally I'd inspect this bullet point in more details, since the remaining points seem to be static in their behavior and thus should be handled by the environment dependent md5sums.

**Comment by okomarov** [comment]
Why don't we use one testing state (using global for all states is a bit confusing) for generating all md5 sums? With a bit of luck we will have just have one set of of checksums across all platforms/environments. 

Basically, with #542 we will have the testing state and all we need is a routine/function that generates the md5 by first injecting the testing state, converting with `m2t`, calculating checksum, and restoring the local state.

**Comment by PeterPablo** [comment]
I recently [noticed](https://github.com/matlab2tikz/matlab2tikz/pull/586#issuecomment-84969853) that axis limits (e.g., `xlim`) change on different platforms, while using the same platform (matlab, octave). This is probably one of the main reasons for tests needing to be marked as unreliable.

**Comment by PeterPablo** [comment]
For inconsistencies of `at`, `get(0,'ScreenPixelsPerInch')` seems to be involved (https://github.com/matlab2tikz/matlab2tikz/pull/639#issuecomment-99350552).
