### ISSUE TITLE
MATLAB CI implementation

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#574]
As hinted in #351 by @PeterPablo, we should ask The MathWorks if we could obtain a MATLAB license (e.g. for use on Travis) to facilitate automatic testing.
Alternatively, they might be able to provide us with different options (e.g. maybe we could use their cloud systems to run our tests, ...).

Chances are quite slim they will be able to provide us with anything, but we might as well try since we are  in the top-10 projects on [FileExchange](http://www.mathworks.com/matlabcentral/fileexchange/index?sort=downloads_desc&term=) (and even third when excluding their own packages). I think we have the best shot if @nschloe does this, unless someone else has better connections?

## TODO
 - [x] Implement `makeTapReport()` --> #749 
 - [x] Finetune Jenkins install
   - [x] use webhooks instead of polling
   - [x] make reports publicly accessible from NAS (in the meanwhile, I can provide a VPN token for access)
   - ~~ split GitHub integration: separate test results for HG1, HG2 and Octave ~~
 - [ ] See why some of the tests fail

**Comment by PeterPablo** [comment]
I agree -- hopefully @nschloe is willing to reach out.

**Comment by egeerardyn** [comment]
I've had contact with @nschloe regarding this topic. He (understandably) doesn't seem to want to sink any time into this. 

Once my university has renewed its campus license and support contract (by the end of this month) and I have some time to write a proper mail, I will try to contact TMW to see if they can offer us any help with automatic testing on MATLAB.

**Comment by egeerardyn** [comment]
I have contacted TMW, but I haven't received a positive reply so far.
On their blogs, I did find something related to [Jenkins](http://blogs.mathworks.com/developer/2015/01/20/the-other-kind-of-continuous-integration/). I think that could form the start of something if we need to roll our own CI server.

**Comment by egeerardyn** [comment]
I have been experimenting with Jenkins yesterday on my Arch box. I think I more or less got things working, but I am worried by the many "reliable" tests that provide different results.
Before we can fully use all that, we need to have a look at this.

Also, I think Jenkins would benefit from getting a [TAP report](https://en.wikipedia.org/wiki/Test_Anything_Protocol), that way the number of failed/passed tests can be reported more clearly. Unfortunately, on Travis CI I can't immediately find similar support, though.

## TODO
 - [ ] Implement `makeTapReport()`
 - [ ] Finetune Jenkins install
   - [ ] use webhooks instead of polling
   - [ ] use NAS as test initiator instead of laptop
   - [ ] make reports publicly accessible from NAS (in the meanwhile, I can provide a VPN token for access)
 - [ ] See why some of the tests fail

**Comment by PeterPablo** [comment]
I found [this](https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin) for Jenkins. May be it is helpful to you.
