### ISSUE TITLE
Tackle all TODOs and FIXMEs in the code

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#617]
We have lots of `TODO`s and `FIXME`s in our code. They will have to go. 

I've used the `TodoReview` plugin of SublimeText to generate the report below (though MATLAB has similar functionality). Links to the code here are just for convenience and not guaranteed to be perfectly in sync.

## FIXME (54)

  * [ ] [src/matlab2tikz.m:380](../blob/develop/src/matlab2tikz.m#L380)             See #471
  * [ ] [src/matlab2tikz.m:745](../blob/develop/src/matlab2tikz.m#L745)             this part (e.g. fall back objects) should be restructured.
  * [ ] [src/matlab2tikz.m:927](../blob/develop/src/matlab2tikz.m#L927)             axis background, axis grid, main, axis ticks, axis lines, axis tick labels, axis descriptions, axis foreground
  * [ ] [src/matlab2tikz.m:3613](../blob/develop/src/matlab2tikz.m#L3613)            external
  * [ ] [src/matlab2tikz.m:4042](../blob/develop/src/matlab2tikz.m#L4042)            can we get sampled horizontal color bars to work?
  * [ ] [src/matlab2tikz.m:4043](../blob/develop/src/matlab2tikz.m#L4043)            sampled colorbars should be inferred, not by using strict!
  * [ ] [src/matlab2tikz.m:5108](../blob/develop/src/matlab2tikz.m#L5108)            this function is currently unused -- remove it in the future?
  * [ ] [src/matlab2tikz.m:5462](../blob/develop/src/matlab2tikz.m#L5462)            Only append '{}' if there's an odd number of backslashes
  * [ ] [test/saveHashTable.m:31](../blob/develop/test/saveHashTable.m#L31)           when does this happen??
  * [ ] [private/execute_plot_stage.m:24](../blob/develop/private/execute_plot_stage.m#L24)  implement #484 to get access to the meta data
  * [ ] [suites/ACID.m:189](../blob/develop/suites/ACID.m#L189)                investigate
  * [ ] [suites/ACID.m:286](../blob/develop/suites/ACID.m#L286)                investigate
  * [ ] [suites/ACID.m:353](../blob/develop/suites/ACID.m#L353)                inspect this
  * [ ] [suites/ACID.m:515](../blob/develop/suites/ACID.m#L515)                investigate
  * [ ] [suites/ACID.m:524](../blob/develop/suites/ACID.m#L524)                investigate
  * [ ] [suites/ACID.m:538](../blob/develop/suites/ACID.m#L538)                investigate
  * [ ] [suites/ACID.m:585](../blob/develop/suites/ACID.m#L585)                investigate
  * [ ] [suites/ACID.m:586](../blob/develop/suites/ACID.m#L586)                this generates many "division by zero" in Octave
  * [ ] [suites/ACID.m:699](../blob/develop/suites/ACID.m#L699)                investigate
  * [ ] [suites/ACID.m:734](../blob/develop/suites/ACID.m#L734)                investigate
  * [ ] [suites/ACID.m:743](../blob/develop/suites/ACID.m#L743)                investigate
  * [ ] [suites/ACID.m:752](../blob/develop/suites/ACID.m#L752)                investigate
  * [ ] [suites/ACID.m:760](../blob/develop/suites/ACID.m#L760)                investigate
  * [ ] [suites/ACID.m:770](../blob/develop/suites/ACID.m#L770)                investigate
  * [ ] [suites/ACID.m:782](../blob/develop/suites/ACID.m#L782)                investigate
  * [ ] [suites/ACID.m:884](../blob/develop/suites/ACID.m#L884)                investigate
  * [ ] [suites/ACID.m:979](../blob/develop/suites/ACID.m#L979)                investigate
  * [ ] [suites/ACID.m:1009](../blob/develop/suites/ACID.m#L1009)               investigate
  * [ ] [suites/ACID.m:1048](../blob/develop/suites/ACID.m#L1048)               investigate
  * [ ] [suites/ACID.m:1065](../blob/develop/suites/ACID.m#L1065)               investigate
  * [ ] [suites/ACID.m:1077](../blob/develop/suites/ACID.m#L1077)               This opens a new figure that doesn't get closed automatically
  * [ ] [suites/ACID.m:1095](../blob/develop/suites/ACID.m#L1095)               This opens a new figure that doesn't get closed automatically
  * [ ] [suites/ACID.m:1207](../blob/develop/suites/ACID.m#L1207)               investigate
  * [ ] [suites/ACID.m:1219](../blob/develop/suites/ACID.m#L1219)               investigate
  * [ ] [suites/ACID.m:1249](../blob/develop/suites/ACID.m#L1249)               investigate
  * [ ] [suites/ACID.m:1301](../blob/develop/suites/ACID.m#L1301)               investigate
  * [ ] [suites/ACID.m:1328](../blob/develop/suites/ACID.m#L1328)               investigate
  * [ ] [suites/ACID.m:1347](../blob/develop/suites/ACID.m#L1347)               investigate
  * [ ] [suites/ACID.m:1669](../blob/develop/suites/ACID.m#L1669)               investigate
  * [ ] [suites/ACID.m:1686](../blob/develop/suites/ACID.m#L1686)               investigate
  * [ ] [suites/ACID.m:1734](../blob/develop/suites/ACID.m#L1734)               investigate
  * [ ] [suites/ACID.m:1744](../blob/develop/suites/ACID.m#L1744)               investigate
  * [ ] [suites/ACID.m:1802](../blob/develop/suites/ACID.m#L1802)               investigate
  * [ ] [suites/ACID.m:1834](../blob/develop/suites/ACID.m#L1834)               investigate
  * [ ] [suites/ACID.m:1899](../blob/develop/suites/ACID.m#L1899)               investigate
  * [ ] [suites/ACID.m:1944](../blob/develop/suites/ACID.m#L1944)               investigate
  * [ ] [suites/ACID.m:1975](../blob/develop/suites/ACID.m#L1975)               investigate
  * [ ] [suites/ACID.m:2018](../blob/develop/suites/ACID.m#L2018)               investigate
  * [ ] [suites/ACID.m:2085](../blob/develop/suites/ACID.m#L2085)               investigate
  * [ ] [suites/ACID.m:2132](../blob/develop/suites/ACID.m#L2132)               investigate
  * [ ] [suites/ACID.m:2218](../blob/develop/suites/ACID.m#L2218)               investigate
  * [ ] [suites/ACID.m:2413](../blob/develop/suites/ACID.m#L2413)               investigate
  * [ ] [suites/ACID.m:2444](../blob/develop/suites/ACID.m#L2444)               investigate
  * [ ] [suites/ACID.m:2488](../blob/develop/suites/ACID.m#L2488)               this test is unreliable because the x/y lims of `ax2` are not set

## TODO (35)

  * [ ] [src/matlab2tikz.m:561](../blob/develop/src/matlab2tikz.m#L561)             fix for octave
  * [ ] [src/matlab2tikz.m:899](../blob/develop/src/matlab2tikz.m#L899)             has{XYZ}Grid is always false without a good reason
  * [ ] [src/matlab2tikz.m:921](../blob/develop/src/matlab2tikz.m#L921)             use proper grid ordering
  * [ ] [src/matlab2tikz.m:1107](../blob/develop/src/matlab2tikz.m#L1107)            How to uniquely connect a legend with a pair of axes in Octave?
  * [ ] [src/matlab2tikz.m:1120](../blob/develop/src/matlab2tikz.m#L1120)            The following logic does not work for 3D plots.
  * [ ] [src/matlab2tikz.m:1402](../blob/develop/src/matlab2tikz.m#L1402)            Don't hardcode "10".
  * [ ] [src/matlab2tikz.m:1533](../blob/develop/src/matlab2tikz.m#L1533)            pre-allocate the cell array such that it doesn't grow during the loop
  * [ ] [src/matlab2tikz.m:1534](../blob/develop/src/matlab2tikz.m#L1534)            scale `maxChunkLength` with the number of columns in the data array
  * [ ] [src/matlab2tikz.m:1854](../blob/develop/src/matlab2tikz.m#L1854)            is the above "crcr" compatible with pgfplots 1.12 ?
  * [ ] [src/matlab2tikz.m:1855](../blob/develop/src/matlab2tikz.m#L1855)           is a "patch table" externalizable?
  * [ ] [src/matlab2tikz.m:1894](../blob/develop/src/matlab2tikz.m#L1894)           this function can probably be split further, just look at all those
  * [ ] [src/matlab2tikz.m:1966](../blob/develop/src/matlab2tikz.m#L1966)           probably this should be integrated with getAndCheckDefault etc.
  * [ ] [src/matlab2tikz.m:2522](../blob/develop/src/matlab2tikz.m#L2522)           rewrite drawTextarrow. Handle all info info directly
  * [ ] [src/matlab2tikz.m:2872](../blob/develop/src/matlab2tikz.m#L2872)           handle Curvature = [0.8 0.4]
  * [ ] [src/matlab2tikz.m:3112](../blob/develop/src/matlab2tikz.m#L3112)           Get this in order as soon as Pgfplots can do "scatter rgb".
  * [ ] [src/matlab2tikz.m:3192](../blob/develop/src/matlab2tikz.m#L3192)           Hm, can't deal with this?
  * [ ] [src/matlab2tikz.m:3267](../blob/develop/src/matlab2tikz.m#L3267)           Get rid of code duplication with 'drawAxes'.
  * [ ] [src/matlab2tikz.m:3282](../blob/develop/src/matlab2tikz.m#L3282)           wait for pgfplots to implement other base values (see #438)
  * [ ] [src/matlab2tikz.m:3491](../blob/develop/src/matlab2tikz.m#L3491)           Get rid of code duplication with 'drawAxes'.
  * [ ] [src/matlab2tikz.m:3602](../blob/develop/src/matlab2tikz.m#L3602)           Look into replacing this by something more 'local',
  * [ ] [src/matlab2tikz.m:3699](../blob/develop/src/matlab2tikz.m#L3699)           this can be simplified using sort
  * [ ] [src/matlab2tikz.m:3738](../blob/develop/src/matlab2tikz.m#L3738)           this can be vectorized
  * [ ] [src/matlab2tikz.m:3875](../blob/develop/src/matlab2tikz.m#L3875)           check this
  * [ ] [src/matlab2tikz.m:4017](../blob/develop/src/matlab2tikz.m#L4017)           HG2: colorbar ticks and colorbar tick labels
  * [ ] [src/matlab2tikz.m:4110](../blob/develop/src/matlab2tikz.m#L4110)           move to top
  * [ ] [src/matlab2tikz.m:4419](../blob/develop/src/matlab2tikz.m#L4419)           Implement these.
  * [ ] [src/matlab2tikz.m:4434](../blob/develop/src/matlab2tikz.m#L4434)           shouldn't this include units?
  * [ ] [src/matlab2tikz.m:5146](../blob/develop/src/matlab2tikz.m#L5146)           check if relevant Axes or all Axes are better.
  * [ ] [test/codeReport.m:46](../blob/develop/test/codeReport.m#L46)             handle all mlint messages and/or other metrics of the code
  * [ ] [test/saveHashTable.m:11](../blob/develop/test/saveHashTable.m#L11)          handle multiple test suites in a single array
  * [ ] [suites/ACID.m:1405](../blob/develop/suites/ACID.m#L1405)               fully test tex conversion instead of a random subsample!
  * [ ] [suites/ACID.m:1726](../blob/develop/suites/ACID.m#L1726)               On processing the matlab2tikz_acidtest output, LaTeX complains
  * [ ] [suites/ACID.m:1760](../blob/develop/suites/ACID.m#L1760)               do we really need this TriScatteredInterp?
  * [ ] [suites/ACID.m:2522](../blob/develop/suites/ACID.m#L2522)               later replace by 'isHG2()'
  * [ ] [suites/ACID.m:2564](../blob/develop/suites/ACID.m#L2564)               later replace by 'isHG2()'

**Comment by bene86** [comment]
regarding this todo: src/matlab2tikz.m:921 use proper grid ordering
I implemented the solution from

I inserted the following into my template preamble:
\makeatletter \newcommand{\pgfplotsdrawaxis}{\pgfplots@draw@axis} \makeatother
\pgfplotsset{axis line on top/.style={
  axis line style=transparent,
  ticklabel style=transparent,
  tick style=transparent,
  axis on top=false,
  after end axis/.append code={
    \pgfplotsset{axis line style=opaque,
      ticklabel style=opaque,
      tick style=opaque,
      grid=none}
    \pgfplotsdrawaxis}
  }
}

and set 'axis line on top' as an 'extraAxisOptions' in matlab2tikz. Now everything looks as I want it. Would that be an idea to implement it into matlab2tikz?

**Comment by egeerardyn** [comment]
@bene86: Thanks for the suggestion. I'm glad there is a workaround for this (that doesn't rely on overplotting another axis).
But for inclusion in `matlab2tikz` I have a few concerns:
 - such code should (ideally) be placed in a preamble, which we cannot access
 - I cannot imagine this is the easiest way to get this working or that nothing has changed since 2011 in this regard,
 - I expect that by simply reordering the pgfplots layers, we could get the same (or very similar) results in a clearer way

**Comment by okomarov** [comment]
As @egeerardyn  points out, pgfplots page 354 `\pgfplotssetlayers{<layer configuration name>}` allows to control grid ordering ([src/matlab2tikz.m:921](https://github.com/matlab2tikz/matlab2tikz/blob/develop/src/matlab2tikz.m#L921))

**Comment by egeerardyn** [comment]
This page will be updated less often in the future.
For an up-to-date overview, please ask [Jenkins](http://pixiebox.synology.me:8090/job/matlab2tikz/138/tasksResult/).
