### ISSUE TITLE
1.0 Release

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#627]
This is a release ticket for the upcoming 1.0 release, such that we don't forget some of the things during release.

 * [x] :point_right: handle the last issue for 1.0 milestone: #560 :point_left: 
 * [x] Look at [1.0 milestone](https://github.com/matlab2tikz/matlab2tikz/milestones/1.0%20Release)
 * [x] Re-validate the whole test suite (headless and graphical!) on R2014a, R2014b and Octave 3.8, e.g. #636, #615, #637 
 * [x] @egeerardyn: update the changelog (I have most of this already in a private branch!)
 * [ ] @nschloe: add the new README.md as FEX description
 * [ ] @nschloe: add a warning at the top of FEX to state that the automatic updater of old versions (<1.0) is not working. Upgrading should be done manually!
 * [ ] Update Zenodo: #551 
 * [ ] Close the release workflow discussions: #583 , #469 
 * [ ] Celebrate :balloon:

**Comment by egeerardyn** [comment]
@nschloe I have uploaded a 1.0.0 release branch.
You can review the changelog there and upload changes yourself if you want.

I am currently running the full test suite on all environments as a last check.

**Comment by PeterPablo** [comment]
@egeerardyn, I also validated the graphical output (for now on R2014b) and noticed that the title vanishes (see #646).

**Comment by egeerardyn** [comment]
Branch: [release-1.0.0](https://github.com/matlab2tikz/matlab2tikz/tree/release-1.0.0)
Commit tested: aa7394531021c1f0b71afb9a76fb3bccc50e57d4 (current tip)

I have run the tests on R2014a and R2014b. Octave is giving me a hard time, though: headless seems to run fine, but graphical does not.

## Headless output
### R2014b HEADLESS

The following tests are known to be unreliable. They, however, do not cause the build to fail.

           ACID(  1) multiline_labels         : OK
           ACID(  6) sine_with_annotation     : OK
           ACID(  9) contourPenny             : OK
           ACID( 10) peaks_contourf           : OK
           ACID( 12) double_colorbar          : OK
           ACID( 16) logplot                  : OK
           ACID( 17) colorbarLogplot          : SKIPPED
           ACID( 18) legendplot               : OK
           ACID( 20) moreLegends              : OK
           ACID( 24) quiver3plot              : OK
           ACID( 34) bars                     : OK
           ACID( 36) errorBars                : OK
           ACID( 38) subplot2x2b              : OK
           ACID( 39) manualAlignment          : OK
           ACID( 40) subplotCustom            : OK
           ACID( 45) besselImage              : OK
           ACID( 47) zplanePlot1              : OK
           ACID( 48) zplanePlot2              : OK
           ACID( 49) freqResponsePlot         : OK
           ACID( 52) multipleAxes             : OK
           ACID( 57) surfPlot                 : OK
           ACID( 58) surfPlot2                : OK
           ACID( 61) ylabels                  : OK
           ACID( 63) mixedBarLine             : OK
           ACID( 67) texrandom                : OK
           ACID( 68) latexInterpreter         : OK
           ACID( 73) rectanglePlot            : OK
           ACID( 88) annotationSubplots       : OK
           ACID( 90) annotationTextUnits      : OK
           ACID( 91) imageOrientation_PNG     : OK
           ACID( 92) imageOrientation_inline  : OK
           ACID( 94) stackedBarsWithOther     : OK
           ACID( 95) colorbarLabelTitle       : OK
           ACID( 96) textAlignment            : OK
           ACID( 97) overlappingPlots         : OK

All tests were successful. :-)


Only the following tests determine the build outcome:

           ACID(  2) plain_cos                : OK
           ACID(  3) sine_with_markers        : OK
           ACID(  4) markerSizes              : OK
           ACID(  5) markerSizes2             : OK
           ACID(  7) linesWithOutliers        : OK
           ACID(  8) peaks_contour            : OK
           ACID( 11) many_random_points       : OK
           ACID( 13) randomWithLines          : OK
           ACID( 14) double_axes              : OK
           ACID( 15) double_axes2             : OK
           ACID( 19) legendplotBoxoff         : OK
           ACID( 21) zoom                     : OK
           ACID( 22) quiveroverlap            : OK
           ACID( 23) quiverplot               : OK
           ACID( 25) logicalImage             : OK
           ACID( 26) imagescplot              : OK
           ACID( 27) imagescplot2             : OK
           ACID( 28) stairsplot               : OK
           ACID( 29) polarplot                : OK
           ACID( 30) roseplot                 : OK
           ACID( 31) compassplot              : OK
           ACID( 32) stemplot                 : OK
           ACID( 33) stemplot2                : OK
           ACID( 35) xAxisReversed            : OK
           ACID( 37) errorBars2               : OK
           ACID( 41) legendsubplots           : OK
           ACID( 42) bodeplots                : OK
           ACID( 43) rlocusPlot               : OK
           ACID( 44) mandrillImage            : OK
           ACID( 46) clownImage               : OK
           ACID( 50) axesLocation             : OK
           ACID( 51) axesColors               : OK
           ACID( 53) scatterPlotRandom        : OK
           ACID( 54) scatterPlot              : OK
           ACID( 55) scatter3Plot             : OK
           ACID( 56) spherePlot               : OK
           ACID( 59) superkohle               : OK
           ACID( 60) meshPlot                 : OK
           ACID( 62) spectro                  : OK
           ACID( 64) decayingharmonic         : OK
           ACID( 65) texcolor                 : OK
           ACID( 66) textext                  : OK
           ACID( 69) latexmath2               : OK
           ACID( 70) parameterCurve3d         : OK
           ACID( 71) parameterSurf            : OK
           ACID( 72) fill3plot                : OK
           ACID( 74) herrorbarPlot            : OK
           ACID( 75) hist3d                   : OK
           ACID( 76) myBoxplot                : OK
           ACID( 77) areaPlot                 : OK
           ACID( 78) customLegend             : OK
           ACID( 79) pixelLegend              : OK
           ACID( 80) croppedImage             : OK
           ACID( 81) pColorPlot               : OK
           ACID( 82) hgTransformPlot          : OK
           ACID( 83) scatterPlotMarkers       : OK
           ACID( 84) multiplePatches          : OK
           ACID( 85) logbaseline              : OK
           ACID( 86) alphaImage               : OK
           ACID( 87) annotationAll            : OK
           ACID( 89) annotationText           : OK
           ACID( 93) texInterpreter           : OK
           ACID( 98) histogramPlot            : OK
           ACID( 99) alphaTest                : OK

All tests were successful. :-)

### MATLAB R2014a

The following tests are known to be unreliable. They, however, do not cause the build to fail.

           ACID(  1) multiline_labels         : OK
           ACID(  8) peaks_contour            : hash 4020887171129ef75886a10503d29afe != (735e181595d6708c87b34b497560141b)
           ACID( 10) peaks_contourf           : OK
           ACID( 12) double_colorbar          : OK
           ACID( 16) logplot                  : OK
           ACID( 17) colorbarLogplot          : OK
           ACID( 18) legendplot               : OK
           ACID( 24) quiver3plot              : OK
           ACID( 29) polarplot                : OK
           ACID( 30) roseplot                 : OK
           ACID( 31) compassplot              : OK
           ACID( 34) bars                     : OK
           ACID( 39) manualAlignment          : OK
           ACID( 40) subplotCustom            : OK
           ACID( 43) rlocusPlot               : OK
           ACID( 45) besselImage              : OK
           ACID( 47) zplanePlot1              : OK
           ACID( 48) zplanePlot2              : OK
           ACID( 49) freqResponsePlot         : OK
           ACID( 56) spherePlot               : OK
           ACID( 57) surfPlot                 : OK
           ACID( 58) surfPlot2                : OK
           ACID( 60) meshPlot                 : OK
           ACID( 62) spectro                  : OK
           ACID( 63) mixedBarLine             : OK
           ACID( 67) texrandom                : OK
           ACID( 69) latexmath2               : OK
           ACID( 70) parameterCurve3d         : OK
           ACID( 71) parameterSurf            : OK
           ACID( 75) hist3d                   : OK
           ACID( 76) myBoxplot                : OK
           ACID( 78) customLegend             : OK
           ACID( 81) pColorPlot               : OK
           ACID( 82) hgTransformPlot          : OK
           ACID( 87) annotationAll            : OK
           ACID( 88) annotationSubplots       : OK
           ACID( 89) annotationText           : OK
           ACID( 90) annotationTextUnits      : OK
           ACID( 94) stackedBarsWithOther     : OK
           ACID( 95) colorbarLabelTitle       : OK
           ACID( 96) textAlignment            : OK

  1 of  41 tests failed. :-(

Only the following tests determine the build outcome:

           ACID(  2) plain_cos                : OK
           ACID(  3) sine_with_markers        : OK
           ACID(  4) markerSizes              : OK
           ACID(  5) markerSizes2             : OK
           ACID(  6) sine_with_annotation     : OK
           ACID(  7) linesWithOutliers        : OK
           ACID(  9) contourPenny             : OK
           ACID( 11) many_random_points       : OK
           ACID( 13) randomWithLines          : OK
           ACID( 14) double_axes              : OK
           ACID( 15) double_axes2             : OK
           ACID( 19) legendplotBoxoff         : OK
           ACID( 20) moreLegends              : OK
           ACID( 21) zoom                     : OK
           ACID( 22) quiveroverlap            : OK
           ACID( 23) quiverplot               : OK
           ACID( 25) logicalImage             : OK
           ACID( 26) imagescplot              : OK
           ACID( 27) imagescplot2             : OK
           ACID( 28) stairsplot               : OK
           ACID( 32) stemplot                 : OK
           ACID( 33) stemplot2                : OK
           ACID( 35) xAxisReversed            : OK
           ACID( 36) errorBars                : OK
           ACID( 37) errorBars2               : OK
           ACID( 38) subplot2x2b              : OK
           ACID( 41) legendsubplots           : OK
           ACID( 42) bodeplots                : OK
           ACID( 44) mandrillImage            : OK
           ACID( 46) clownImage               : OK
           ACID( 50) axesLocation             : OK
           ACID( 51) axesColors               : OK
           ACID( 52) multipleAxes             : OK
           ACID( 53) scatterPlotRandom        : OK
           ACID( 54) scatterPlot              : OK
           ACID( 55) scatter3Plot             : OK
           ACID( 59) superkohle               : OK
           ACID( 61) ylabels                  : OK
           ACID( 64) decayingharmonic         : OK
           ACID( 65) texcolor                 : OK
           ACID( 66) textext                  : OK
           ACID( 68) latexInterpreter         : OK
           ACID( 72) fill3plot                : OK
           ACID( 73) rectanglePlot            : OK
           ACID( 74) herrorbarPlot            : OK
           ACID( 77) areaPlot                 : OK
           ACID( 79) pixelLegend              : OK
           ACID( 80) croppedImage             : OK
           ACID( 83) scatterPlotMarkers       : OK
           ACID( 84) multiplePatches          : OK
           ACID( 85) logbaseline              : OK
           ACID( 86) alphaImage               : OK
           ACID( 91) imageOrientation_PNG     : OK
           ACID( 92) imageOrientation_inline  : OK
           ACID( 93) texInterpreter           : OK
           ACID( 97) overlappingPlots         : OK
           ACID( 98) histogramPlot            : SKIPPED
           ACID( 99) alphaTest                : OK

All tests were successful. :-)

### Octave 3.8.0

The following tests are known to be unreliable. They, however, do not cause the build to fail.

           ACID(  1) multiline_labels         : OK
           ACID(  6) sine_with_annotation     : OK
           ACID(  8) peaks_contour            : OK
           ACID( 17) colorbarLogplot          : OK
           ACID( 18) legendplot               : OK
           ACID( 21) zoom                     : OK
           ACID( 25) logicalImage             : OK
           ACID( 26) imagescplot              : OK
           ACID( 27) imagescplot2             : OK
           ACID( 34) bars                     : OK
           ACID( 38) subplot2x2b              : OK
           ACID( 39) manualAlignment          : OK
           ACID( 41) legendsubplots           : OK
           ACID( 45) besselImage              : OK
           ACID( 56) spherePlot               : OK
           ACID( 58) surfPlot2                : OK
           ACID( 63) mixedBarLine             : OK
           ACID( 67) texrandom                : hash ba1dd1d4e651de04de98cc90a612e78d != (29f1b79c7c5a4164f670e16af1dbe3b9)
           ACID( 74) herrorbarPlot            : hash 0901e645e5b9df5ca2b944a246016300 != (7fb457a82767545cfb202e6242a09833)  plot failed
           ACID( 78) customLegend             : OK
           ACID( 81) pColorPlot               : plot failed
           ACID( 83) scatterPlotMarkers       : plot failed
           ACID( 86) alphaImage               : OK
           ACID( 91) imageOrientation_PNG     : OK
           ACID( 92) imageOrientation_inline  : OK
           ACID( 94) stackedBarsWithOther     : OK
           ACID( 95) colorbarLabelTitle       : OK
           ACID( 96) textAlignment            : OK

  4 of  28 tests failed. :-( 


Only the following tests determine the build outcome:

           ACID(  2) plain_cos                : OK
           ACID(  3) sine_with_markers        : OK
           ACID(  4) markerSizes              : OK
           ACID(  5) markerSizes2             : OK
           ACID(  7) linesWithOutliers        : OK
           ACID(  9) contourPenny             : SKIPPED
           ACID( 10) peaks_contourf           : OK
           ACID( 11) many_random_points       : OK
           ACID( 12) double_colorbar          : SKIPPED
           ACID( 13) randomWithLines          : OK
           ACID( 14) double_axes              : OK
           ACID( 15) double_axes2             : OK
           ACID( 16) logplot                  : OK
           ACID( 19) legendplotBoxoff         : OK
           ACID( 20) moreLegends              : OK
           ACID( 22) quiveroverlap            : OK
           ACID( 23) quiverplot               : OK
           ACID( 24) quiver3plot              : OK
           ACID( 28) stairsplot               : OK
           ACID( 29) polarplot                : OK
           ACID( 30) roseplot                 : OK
           ACID( 31) compassplot              : OK
           ACID( 32) stemplot                 : OK
           ACID( 33) stemplot2                : OK
           ACID( 35) xAxisReversed            : OK
           ACID( 36) errorBars                : OK
           ACID( 37) errorBars2               : OK
           ACID( 40) subplotCustom            : OK
           ACID( 42) bodeplots                : SKIPPED
           ACID( 43) rlocusPlot               : SKIPPED
           ACID( 44) mandrillImage            : SKIPPED
           ACID( 46) clownImage               : SKIPPED
           ACID( 47) zplanePlot1              : SKIPPED
           ACID( 48) zplanePlot2              : SKIPPED
           ACID( 49) freqResponsePlot         : SKIPPED
           ACID( 50) axesLocation             : OK
           ACID( 51) axesColors               : OK
           ACID( 52) multipleAxes             : OK
           ACID( 53) scatterPlotRandom        : OK
           ACID( 54) scatterPlot              : SKIPPED
           ACID( 55) scatter3Plot             : OK
           ACID( 57) surfPlot                 : OK
           ACID( 59) superkohle               : SKIPPED
           ACID( 60) meshPlot                 : OK
           ACID( 61) ylabels                  : OK
           ACID( 62) spectro                  : SKIPPED
           ACID( 64) decayingharmonic         : OK
           ACID( 65) texcolor                 : OK
           ACID( 66) textext                  : OK
           ACID( 68) latexInterpreter         : OK
           ACID( 69) latexmath2               : OK
           ACID( 70) parameterCurve3d         : OK
           ACID( 71) parameterSurf            : SKIPPED
           ACID( 72) fill3plot                : SKIPPED
           ACID( 73) rectanglePlot            : OK
           ACID( 75) hist3d                   : SKIPPED
           ACID( 76) myBoxplot                : SKIPPED
           ACID( 77) areaPlot                 : OK
           ACID( 79) pixelLegend              : OK
           ACID( 80) croppedImage             : SKIPPED
           ACID( 82) hgTransformPlot          : SKIPPED
           ACID( 84) multiplePatches          : OK
           ACID( 85) logbaseline              : OK
           ACID( 87) annotationAll            : SKIPPED
           ACID( 88) annotationSubplots       : SKIPPED
           ACID( 89) annotationText           : SKIPPED
           ACID( 90) annotationTextUnits      : SKIPPED
           ACID( 93) texInterpreter           : OK
           ACID( 97) overlappingPlots         : OK
           ACID( 98) histogramPlot            : SKIPPED
           ACID( 99) alphaTest                : OK

All tests were successful. :-)

## Graphical output

 * [R2014a](https://dl.dropboxusercontent.com/u/452005/m2t/1.0.0-rc/v.1.0.0-rc-R2014a.pdf)
 * [R2014b](https://dl.dropboxusercontent.com/u/452005/m2t/1.0.0-rc/v.1.0.0-rc-R2014b.pdf)

**Comment by PeterPablo** [comment]
R2014b is missing the horizontal line in ACID(32,33). Apart from that, the output looks good to me (consider the known/documented remaining issues).

**Comment by egeerardyn** [comment]
@PeterPablo : If I'm not mistaken, that base line has `handleVisible` set to `off` (or that is the case in HG1 at least).

**Comment by PeterPablo** [comment]
What just came to my mind -- did you also check the other testsuites `testPatches` and `testSurfshader`? I didn't have a single look at them the last months...

**Comment by egeerardyn** [comment]
Good point. I should.

**Comment by okomarov** [comment]
Things might/will fail, especially patch, because the suites are designed to push m2t capabilities. So, do not overweight their value.

Sent from my iPhone

On 13 May 2015, at 13:48, "Egon Geerardyn" <notifications@github.com<mailto:notifications@github.com>> wrote:


Good point. I should.

**Comment by PeterPablo** [comment]
So.... :-) What's our plan of action to get the release out of the door? Is #660 blocking, where I am waiting on advice?

**Comment by egeerardyn** [comment]
@PeterPablo The plan of action is to wait for @nschloe. He is the only one who can update the FEX page, which is something that has to happen during this release (we really have to alert our users that updates should be performed by hand). He told me a few weeks ago he has been extremely busy with other responsibilities and since then I have not seen him online. I mailed him again this morning regarding the release.
In any case, when @nschloe and I push out a release, we should also discuss how to make this process go more smoothly.

I will revisit #660 again tonight and see what has to happen. If it's finished, it can go in 1.0, otherwise it will be for 1.1.

**Comment by nschloe** [comment]
Hi peeps,

I came back from the ill, checked 1.0.0 last night and tomorrow, and just released it. Congratulations to everyone involved! Years ago I had planned to kick out a 1.0 release only when _all_ features of MATLAB are supported by m2t, and although we aren't there quite yet, we're pretty close. I'm really delighted to see this progress and your enthusiasm! I'm especially glad that tests on master are green now for the very first time.

**Comment by egeerardyn** [comment]
Hi Nico, glad to have you back among the living :+1: 

Apparently, my last-minute date patch wasn't in the release, so I did some force-pushes to restore this. Especially the `1.0.0` might need some love on your side:
```shell
git tag -d 1.0.0
git fetch --all --prune
```
I'm sorry for the inconvenience, but it think this will avoid confusion with our users.
