### ISSUE TITLE
Getting rid of the backlog of PRs

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#685]
Since we have quite a standing backlog of PRs, I think we should methodically try to get rid of them (in the good way, not a "shoot in the head, wrap in a carpet and throw in the river" kind of way).

For the current PRs, I propose to:
 - first merge in the latests PRs that were issued post-1.0.0 to keep the history quite linear, i.e. :
   *  [x] #683 
 - then rebase the previously existing PRs on top of `develop` and on the `matlab2tikz` (I prefer the postfix `rb` in those branch names, but that's a matter of preference):
   * [x] #660 i.e. `line-simp_reliable` 
   * [ ] #669 i.e. `octave_guessType`
   * [x] #656 i.e. `PeterPablo/octave_improve_scatterPlotMarkers` 
   * [x] #641 i.e. `PeterPablo/ACID_mock_global_state`
   * [x] #663 i.e. `PeterPablo/ACID_use_pdflatex`
 - review and merge the resulting rebased PRs into `develop` (if we can rebase, review, merge a PR at a time, that's even cleaner still, but anything goes).
 - ~~finally close #666~~

If you have a reason to change the order in which the PRs are to be merged, please feel free to rearrange them above. If you have other suggestions: those are welcome as always. :smile_cat:

**Comment by egeerardyn** [comment]
I'll close this piggy, since only #669 is on the TODO (so having this issue open, doesn't add any more information).
