### ISSUE TITLE
Octave 3.8/4.0 PPA on Travis CI

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#745]
It seems the [Octave PPA](https://launchpad.net/~octave/+archive/ubuntu/stable) we use on Travis, has been upgraded to Octave 4.0.

As long as #695 (and maybe some other stuff) is not integrated, Travis is expected to fail.
There are a few things we could do:
 - find a PPA that still serves Octave 3.8 and use that in the meanwhile
 - put all effort in Octave 4

If we find an Octave 3.8 PPA, we could even make a build matrix and test both Octave 3.8 and 4.0 at the same time on Travis. Not a bad idea, I think.

**Comment by egeerardyn** [comment]
An example build: https://travis-ci.org/matlab2tikz/matlab2tikz/builds/76938273

**Comment by okomarov** [comment]
Why are we using the PPA in the first place :sweat_smile:?

**Comment by egeerardyn** [comment]
Because Travis uses the an (old) LTS release (12.04 I think), which has Octave 3.2 in its official repos if I remember correctly.
Since we no longer support Octave 3.2, it makes little sense to test using that old version, so that's the reason we are using that PPA :smile_cat:

**Comment by okomarov** [comment]
Codeship uses Ubuntu 14.04: https://codeship.com/documentation/security/vm-and-Infrastructure/ 

I am happy to get a feel with it (on a side basic project) if you think that Kenkins might take a while to setup.

**Comment by egeerardyn** [comment]
I think I should be able to setup Jenkins on a home machine by the end of the week (I keep progress in #574). Currently, it should already build the PRs from everybody who is a member of the matlab2tikz organization, but I didn't have the time yesterday evening to check out the problems I am having with R2014a hashes on there.

Also, Arch Linux (what I'm using on that box) has Octave 4.0 already, so that part is not solved yet. That means that checking out CodeShip is still worthwhile. In case you need anything special from my part, just let me know!

**Comment by egeerardyn** [comment]
@okomarov I also tried with Codeship, but what worries me is that the documentation doesn't mention `apt-get` anywhere, so I would be surprised if my build would actually run. We will see.

**Comment by egeerardyn** [comment]
Now it seems to trigger (I have the impression that happens when one of the branches changes, not on a PR). However, there is no Octave installed on Codehsip and there is no way to use `apt-get` (no root privileges). I have asked them whether it's possible to install it.

**Comment by egeerardyn** [comment]
## TODO 
We might want to contact the person behind the Octave PPA for a few things:
 - [ ]  ask for an old Octave 3.8 DEB if he still has it lying around,
 - [ ] tell them about the issues we are having with the provided 4.0 DEB (i.e. the crashes it produces on Travis).

Other thing:
 - [ ] doublecheck on my Jenkins server whether Octave 4 is also an issue there or this is specific to the DEB version (I think the latter).

**Comment by okomarov** [comment]
Sent a message to [Mike Miller](https://launchpad.net/~mtmiller) pointing to the PR where I tested a bit with Travis. Also, asked if he could keep the 3.8 version up together with the newer one.

**Comment by egeerardyn** [comment]
@okomarov Thanks for taking that out of my hands :+1:

**Comment by okomarov** [comment]
Removing OpenBlas with `apt-get purge libopenblas-base` solves the issue.

**Comment by egeerardyn** [comment]
I've got a response from CodeShip as well: they will look into adding Octave to their VM, but they couldn't promise anything just yet.

**Comment by okomarov** [comment]
:+1:

**Comment by egeerardyn** [comment]
I got a message from Codeship they will roll out Octave starting tomorrow morning.

**Comment by egeerardyn** [comment]
This can be closed. 

Octave 3.8.1 works on Codeship without a problem (it only builds pushes, not pull requests). But as Octave 3.8 is also covered by Jenkins, I don't think this is a problem at all.
