### ISSUE TITLE
Pgfplots meta should be set per plot

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#784]
Pgfplots allow to define the range of the meta data (i.e. size used for changing sizes/colors of lines but also for quiver sizes) either for the whole axis or per plot.

We should set this per plot, since this affects the colormap used on quiver plots overlaid on contour plots.

E.g. with our current `ACID(23)` at 1fcb32ae1e8f557b8c57d0d215f35ae11237779b, I get the following output:

![acid23 test-default](https://cloud.githubusercontent.com/assets/177360/10245729/c18026d8-690a-11e5-9732-7dcd32307f96.png)

Adding `point meta min=0,point meta max=10,`to the options of the quiver (not axis!), I get:

![acid23 test-metamax10](https://cloud.githubusercontent.com/assets/177360/10245781/1008abf4-690b-11e5-83f7-72874e641362.png)

You can see that not only the quiver sizes change as expected, but also the colormap of the contour is changed.

To avoid this, we can add `point meta rel=per plot`  to the axis options according to the pgfplots manual:
> `/pgfplots/point meta rel=axis wide|per plot` (initially `axis wide`)
> As already explained in the documentation for `point meta`, one application for point meta data is to determine colors using the current color map and a linear map from point meta data into the current color map. The question is how this linear map is computed.
> The key `point meta rel` configures whether the interval of all point meta coordinates, ![$[m_{\min},m_{\max}]$](http://www.sciweavers.org/tex2img.php?eq=%5Bm_%7B%5Cmin%7D%2C%20m_%7B%5Cmax%7D%5D&bc=White&fc=Black&im=png&fs=11&ff=mathptmx&edit=0) is computed as maximum over all plots in the complete axis (the choice `axis wide`) or only for one particular plot (the choice `per plot`).
> <img width="585" alt="pgfplots manual: per plot vs axis wide" src="https://cloud.githubusercontent.com/assets/177360/10245955/018293e0-690d-11e5-9f41-3eb839040a8f.png">

For this example, this produces (for the last plot): rescaled quivers and right color map.

![acid23 test-perplot](https://cloud.githubusercontent.com/assets/177360/10245804/6ee2db40-690b-11e5-9e64-b4b20394ea7c.png)

# TODO
This is a concrete breakdown of the work that needs to be done
* [ ] add `point meta rel=per plot` to axis options when needed
* [ ] explicitly add `point meta min/max` to plot options where needed
* [ ] make sure the graphics look the same
* [ ] update hashes to reflect these changes
